@startuml
'https://plantuml.com/sequence-diagram

participant client
participant server
participant mongodb

activate client
    client -> server : call endpoint with userid\ntoken in auth header\n<back:cyan>/user/register
    activate server

@enduml