@startuml

'sequence diagram to display the flow of registering a user on the app'

actor user
participant client
participant firebase
participant server
participant database

group register-user
    user -> client: inputs registration details
    activate client
        client -> client: validates user input
        client -> firebase: calls firebase to authenticate user
        activate firebase
            firebase -> firebase: creates a new user and signs in user
            firebase --> client: sends response and \n authentication details
        deactivate firebase
        client -> server: user information & auth header
        activate server
        server -> server: decode token and \n get userid
        server -> database: userinformation
        activate database
        database --> server: userid
        server --> client: success message
        client --> user: registration successful.
    deactivate client
end
@enduml